[workspace]
resolver = "2"
members = [
    "algorithms/random_values",
    "algorithms/vector_sorting",
    "projects/ip_sniffer", 
    "projects/snake_game"
]

[workspace.dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
piston_window = "*"